openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /overlay/create:
    post:
      summary: Create overlay settings
      description: Endpoint to create new overlay settings.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                position:
                  type: string
                  description: Position of the overlay.
                size:
                  type: string
                  description: Size of the overlay.
                content:
                  type: string
                  description: Content of the overlay.
      responses:
        '201':
          description: Overlay settings created successfully.
        '400':
          description: Bad request - Missing data for creating overlay.
        '500':
          description: Internal server error - Failed to create overlay settings.
